### PR TITLE
Improved Fake ILogger behaviour

### PR DESCRIPTION
**Pull request by BetimBeja**
Hello @AndreasVolkmann,
please review this improvement and merge it to your branch so it gets updated on your PR on Jordi's repository.

### CODE REVIEW

**Comment by BetimBeja** [comment]
Hi there @AndreasVolkmann

**Comment by AndreasVolkmann** [comment]
@BetimBeja Sure we can merge this, but I don't see any point in continuing effort here, seeing as there are no more releases.

**Comment by jordimontana82** [comment]
@AndreasVolkmann @BetimBeja v1 releases were on hold due to work on v2 and mostly demand being much higher than current capacity. But I'm glad to announce public preview of 2.x on the 20th of Nov.  Feel free to join to see the new architecture: https://events.powercommunity.com/sessions/new-fakexrmeasy-architecture-overview-and-roadmap/

**Comment by jordimontana82** [comment]
@AndreasVolkmann there are now 6 new repos and 30 new packages published on nuget as rc1. Would love your feedback!

Here's the new home repo:

https://github.com/DynamicsValue/fake-xrm-easy

**Pull request merged**
